// Writes the licenses of the packages bundled into mermaid.min.js, which
// Mermaid's own package doesn't include, to tools/licenses/mermaid-bundled.txt.
// Run it after changing the Mermaid version in tools/fetch-libraries.sh:
//
//   node tools/mermaid-notices.mjs
//
// It installs that Mermaid version's dependencies in a temporary folder.

import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fetchScript = readFileSync(path.join(repo, "tools", "fetch-libraries.sh"), "utf8");
const pin = /^\s*mermaid\s+(\S+)\s/m.exec(fetchScript);
if (!pin) {
  console.error("mermaid-notices: couldn't find Mermaid's version in PACKAGES in tools/fetch-libraries.sh.");
  process.exit(1);
}
const version = pin[1];

const work = mkdtempSync(path.join(tmpdir(), "mermaid-notices-"));
try {
  writeFileSync(path.join(work, "package.json"), "{}");
  execFileSync("npm", ["install", "--omit=dev", "--ignore-scripts", "--no-audit", "--no-fund",
    `mermaid@${version}`], { cwd: work, stdio: "ignore" });

  const seen = new Map();
  const visit = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const full = path.join(dir, entry.name);
      if (entry.name.startsWith("@")) { visit(full); continue; }
      const manifest = path.join(full, "package.json");
      if (existsSync(manifest)) {
        const pkg = JSON.parse(readFileSync(manifest, "utf8"));
        // Type definitions aren't bundled, and Mermaid's own license is
        // included next to mermaid.min.js.
        if (pkg.name && pkg.name !== "mermaid" && !pkg.name.startsWith("@types/")) {
          const files = readdirSync(full).filter((name) => /^(licen[cs]e|copying|notice)/i.test(name)).sort();
          seen.set(`${pkg.name}@${pkg.version}`, {
            license: typeof pkg.license === "string" ? pkg.license
              : pkg.license ? JSON.stringify(pkg.license) : "not stated in package.json; see below",
            texts: files.map((name) => readFileSync(path.join(full, name), "utf8").trim()),
          });
        }
      }
      const nested = path.join(full, "node_modules");
      if (existsSync(nested)) visit(nested);
    }
  };
  visit(path.join(work, "node_modules"));

  let out = `Packages bundled into mermaid.min.js ${version}\n` +
    "Generated by tools/mermaid-notices.mjs from Mermaid's dependency tree.\n" +
    "DOMPurify, offered under MPL-2.0 or Apache-2.0, is used under the\n" +
    "Apache License 2.0.\n";
  for (const [name, { license, texts }] of [...seen].sort(([a], [b]) => a.localeCompare(b))) {
    out += `\n${"=".repeat(78)}\n${name}\nLicense: ${license}\n${"=".repeat(78)}\n\n`;
    out += texts.length ? texts.join("\n\n") + "\n" : "(The package includes no license file.)\n";
  }
  writeFileSync(path.join(repo, "tools", "licenses", "mermaid-bundled.txt"), out);
  console.log(`${seen.size} packages written to tools/licenses/mermaid-bundled.txt`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
